import { profile, type CourseCatalogProfile } from './courseProfiles.ts'
import type { SubjectDomain } from '../types.ts'

type Definition = [string, string, string[], SubjectDomain, string, string?]

const definitions: Definition[] = [
  ['math.calculus', '高等数学', ['高数', '微积分'], '数学与统计', '理学'],
  ['math.linear-algebra', '线性代数', ['线代'], '数学与统计', '理学'],
  ['math.probability', '概率论与数理统计', ['概率论', '概率统计'], '数学与统计', '理学'],
  ['math.discrete', '离散数学', ['离散'], '数学与统计', '理学'],
  ['math.statistics', '统计学', ['大学统计学'], '数学与统计', '理学'],
  ['math.numerical', '数值分析', ['数值计算'], '数学与统计', '理学'],
  ['physics.college', '大学物理', ['大物'], '物理', '理学'],
  ['physics.experiment', '大学物理实验', ['大物实验'], '物理', '理学'],
  ['chemistry.general', '大学化学', ['普通化学'], '化学', '理学'],
  ['chemistry.organic', '有机化学', ['有机'], '化学', '理学'],
  ['biology.general', '普通生物学', ['大学生物'], '生物科学', '理学'],
  ['language.college-english', '大学英语', ['大英'], '大学英语与语言考试', '语言'],
  ['language.cet4', '大学英语四级', ['四级', 'CET4', 'CET-4'], '大学英语与语言考试', '语言考试'],
  ['language.cet6', '大学英语六级', ['六级', 'CET6', 'CET-6'], '大学英语与语言考试', '语言考试'],
  ['language.ielts', '雅思', ['IELTS'], '大学英语与语言考试', '语言考试'],
  ['language.japanese', '大学日语', ['日语'], '大学英语与语言考试', '语言'],
  ['programming.c', 'C语言程序设计', ['C语言', 'C'], '编程语言与Web开发', '计算机'],
  ['programming.cpp', 'C++程序设计', ['C++'], '编程语言与Web开发', '计算机'],
  ['programming.java', 'Java程序设计', ['Java'], '编程语言与Web开发', '计算机'],
  ['programming.python', 'Python程序设计', ['Python'], '编程语言与Web开发', '计算机'],
  ['programming.javascript', 'JavaScript程序设计', ['JavaScript', 'JS'], '编程语言与Web开发', '计算机'],
  ['programming.web', 'Web前端开发', ['前端开发', 'Web开发'], '编程语言与Web开发', '计算机'],
  ['cs.data-structures', '数据结构', ['数据结构与算法'], '编程语言与Web开发', '计算机'],
  ['cs.algorithms', '算法设计与分析', ['算法'], '编程语言与Web开发', '计算机'],
  ['cs.operating-systems', '操作系统', ['OS'], '计算机系统网络与数据库', '计算机'],
  ['cs.networks', '计算机网络', ['计网'], '计算机系统网络与数据库', '计算机'],
  ['cs.computer-organization', '计算机组成原理', ['计组'], '计算机系统网络与数据库', '计算机'],
  ['cs.software-engineering', '软件工程', ['软工'], '编程语言与Web开发', '计算机'],
  ['database.principles', '数据库系统原理', ['数据库', 'DB'], '计算机系统网络与数据库', '计算机'],
  ['database.sql', 'SQL与数据库应用', ['SQL'], '计算机系统网络与数据库', '计算机'],
  ['ai.fundamentals', '人工智能导论', ['人工智能基础'], '人工智能与数据科学', '计算机'],
  ['ai.machine-learning', '机器学习', ['ML'], '人工智能与数据科学', '计算机'],
  ['ai.deep-learning', '深度学习', ['DL'], '人工智能与数据科学', '计算机'],
  ['data.data-analysis', '数据分析基础', ['数据分析'], '人工智能与数据科学', '数据科学'],
  ['data.data-mining', '数据挖掘', ['数据采掘'], '人工智能与数据科学', '数据科学'],
  ['electronics.circuits', '电路分析基础', ['电路'], '电子信息与通信', '电子信息'],
  ['electronics.analog', '模拟电子技术', ['模电'], '电子信息与通信', '电子信息'],
  ['electronics.digital', '数字电子技术', ['数电'], '电子信息与通信', '电子信息'],
  ['electronics.signals', '信号与系统', ['信号系统'], '电子信息与通信', '电子信息'],
  ['communications.principles', '通信原理', ['通信'], '电子信息与通信', '电子信息'],
  ['automation.control', '自动控制原理', ['自控'], '自动化与控制', '自动化'],
  ['automation.plc', 'PLC原理与应用', ['PLC'], '自动化与控制', '自动化'],
  ['mechanics.theoretical', '理论力学', ['理力'], '机械与制造', '机械'],
  ['mechanics.materials', '材料力学', ['材力'], '机械与制造', '机械'],
  ['mechanics.design', '机械设计基础', ['机械设计'], '机械与制造', '机械'],
  ['mechanics.drawing', '工程制图', ['机械制图'], '机械与制造', '机械'],
  ['civil.structural', '结构力学', ['结力'], '土木与建筑', '土木'],
  ['civil.concrete', '混凝土结构设计', ['混凝土结构'], '土木与建筑', '土木'],
  ['architecture.design', '建筑设计基础', ['建筑设计'], '土木与建筑', '建筑'],
  ['economics.micro', '微观经济学', ['微经'], '经济金融会计与管理', '经管'],
  ['economics.macro', '宏观经济学', ['宏经'], '经济金融会计与管理', '经管'],
  ['finance.corporate', '公司金融', ['公司理财'], '经济金融会计与管理', '经管'],
  ['accounting.basic', '基础会计学', ['会计学原理'], '经济金融会计与管理', '经管'],
  ['management.principles', '管理学原理', ['管理学'], '经济金融会计与管理', '经管'],
  ['marketing.principles', '市场营销学', ['市场营销'], '经济金融会计与管理', '经管'],
  ['law.civil', '民法学', ['民法'], '法学', '法学'],
  ['law.criminal', '刑法学', ['刑法'], '法学', '法学'],
  ['law.constitution', '宪法学', ['宪法'], '法学', '法学'],
  ['medicine.anatomy', '人体解剖学', ['解剖'], '医学', '医学'],
  ['medicine.physiology', '生理学', ['人体生理学'], '医学', '医学'],
  ['medicine.pathology', '病理学', ['病理'], '医学', '医学'],
  ['medicine.pharmacology', '药理学', ['药理'], '护理与药学', '医学'],
  ['nursing.fundamentals', '基础护理学', ['护理基础'], '护理与药学', '医学'],
  ['psychology.general', '普通心理学', ['心理学基础'], '心理学与教育学', '社科'],
  ['education.principles', '教育学原理', ['教育学'], '心理学与教育学', '社科'],
  ['journalism.intro', '新闻学概论', ['新闻学'], '新闻传播与汉语言文学', '人文'],
  ['literature.modern-chinese', '中国现代文学', ['现代文学'], '新闻传播与汉语言文学', '人文'],
  ['literature.ancient-chinese', '中国古代文学', ['古代文学'], '新闻传播与汉语言文学', '人文'],
  ['sports.physiology', '运动生理学', ['体育生理学'], '体育科学', '体育'],
  ['design.photoshop', 'Adobe Photoshop', ['Photoshop', 'PS'], '平面与图像设计', '设计', 'Adobe'],
  ['design.illustrator', 'Adobe Illustrator', ['Illustrator', 'AI矢量'], '矢量设计', '设计', 'Adobe'],
  ['design.premiere', 'Adobe Premiere Pro', ['Premiere', 'PR'], '视频剪辑与动效', '设计', 'Adobe'],
  ['design.after-effects', 'Adobe After Effects', ['After Effects', 'AE'], '视频剪辑与动效', '设计', 'Adobe'],
  ['design.figma', 'Figma界面设计', ['Figma'], 'UIUX与交互设计', '设计', 'Figma'],
  ['cad.rhino', 'Rhino', ['Rhino三维建模', '犀牛', '犀牛建模'], '三维建模与CAD', '设计工程', 'McNeel'],
  ['cad.autocad', 'AutoCAD工程制图', ['AutoCAD', 'CAD制图'], '三维建模与CAD', '设计工程', 'Autodesk'],
  ['cad.blender', 'Blender三维建模', ['Blender'], '三维建模与CAD', '设计', 'Blender'],
  ['render.keyshot', 'KeyShot渲染', ['KeyShot'], '三维建模与CAD', '设计', 'Luxion'],
  ['productivity.excel', 'Microsoft Excel', ['Excel'], '数学与统计', '数据分析', 'Microsoft'],
  ['statistics.spss', 'SPSS数据分析', ['SPSS'], '数学与统计', '数据分析', 'IBM'],
  ['math.matlab', 'MATLAB科学计算', ['MATLAB'], '数学与统计', '数据分析', 'MathWorks'],
  ['cad.3ds-max', 'Autodesk 3ds Max', ['3ds Max', '3dsmax'], '三维建模与CAD', '设计', 'Autodesk'],
  ['cad.cinema-4d', 'Cinema 4D', ['C4D', 'Cinema4D'], '三维建模与CAD', '设计', 'Maxon'],
  ['cad.solidworks', 'SOLIDWORKS', ['SolidWorks'], '三维建模与CAD', '设计工程', 'Dassault Systèmes'],
  ['cad.sketchup', 'SketchUp', ['SketchUp'], '三维建模与CAD', '设计工程', 'Trimble'],
  ['programming.vue', 'Vue.js前端开发', ['Vue', 'Vue.js'], '编程语言与Web开发', '计算机'],
  ['programming.react', 'React前端开发', ['React', 'React.js'], '编程语言与Web开发', '计算机'],
  ['programming.unity', 'Unity游戏开发', ['Unity'], '编程语言与Web开发', '计算机'],
  ['programming.ue5', 'Unreal Engine 5开发', ['UE5', 'Unreal Engine'], '编程语言与Web开发', '计算机'],
  ['theory.current-affairs', '形势与政策', ['形策'], '经济金融会计与管理', '思想政治'],
  ['psychology.college-health', '大学生心理健康教育', ['大学生心理健康'], '心理学与教育学', '通识'],
  ['productivity.powerpoint', 'Microsoft PowerPoint', ['PowerPoint', 'PPT'], '通用技能', '办公技能', 'Microsoft'],
  ['product.design-methods', '产品设计方法', ['设计方法'], '产品设计理论与项目', '设计'],
  ['product.portfolio', '作品集设计', ['作品集'], '产品设计理论与项目', '设计'],
  ['theory.marx', '马克思主义基本原理', ['马原'], '经济金融会计与管理', '思想政治'],
  ['theory.mao', '毛泽东思想和中国特色社会主义理论体系概论', ['毛概'], '经济金融会计与管理', '思想政治'],
  ['theory.history', '中国近现代史纲要', ['近代史纲要', '史纲'], '新闻传播与汉语言文学', '思想政治'],
  ['career.research-methods', '研究方法与论文写作', ['论文写作', '研究方法'], '通用技能', '通识'],
  ['career.presentation', '演讲与表达', ['演讲', '表达训练'], '通用技能', '通识'],
  ['project.innovation', '创新创业项目', ['创新创业'], '产品设计理论与项目', '通识'],
]

const categoryFor = (domain: SubjectDomain): CourseCatalogProfile['category'] => {
  if (domain === '数学与统计') return '数学类'
  if (domain === '大学英语与语言考试') return '语言类'
  if (['编程语言与Web开发', '计算机系统网络与数据库', '人工智能与数据科学'].includes(domain)) return '编程类'
  if (['平面与图像设计', '矢量设计', '三维建模与CAD', '视频剪辑与动效', 'UIUX与交互设计'].includes(domain)) return '设计软件类'
  if (domain === '产品设计理论与项目') return '项目/作品类'
  return domain === '通用技能' ? '通用技能类' : '理论学科类'
}

export const universityCourseProfiles: CourseCatalogProfile[] = definitions.map(([canonicalId, name, aliases, rawDomain, disciplineGroup, toolFamily]) => {
  const domain = rawDomain
  const programming = ['编程语言与Web开发', '计算机系统网络与数据库', '人工智能与数据科学'].includes(domain)
  const design = ['平面与图像设计', '矢量设计', '三维建模与CAD', '视频剪辑与动效', 'UIUX与交互设计'].includes(domain)
  return profile({
    canonicalId,
    name,
    aliases,
    stage: '大学',
    domain,
    category: categoryFor(domain),
    disciplineGroup,
    prerequisites: [],
    units: [],
    assessments: ['以用户课程大纲、任课教师要求和考试形式为准'],
    diagnosticTemplates: programming ? ['概念判断', '代码阅读', '编码与测试任务'] : design ? ['工具操作任务', '工作流检查', '作品质量检查'] : ['基础概念判断', '典型应用任务', '复盘说明'],
    outcomes: programming ? ['完成可运行实现', '补充边界测试', '说明调试过程'] : design ? ['完成可编辑成果', '按规范检查并导出', '说明关键决策'] : ['解释核心概念', '完成典型任务', '通过复测验证掌握情况'],
    resourceKeywords: [name, ...aliases.slice(0, 2)],
    forbiddenKeywords: design ? ['高等数学速成', '考研数学'] : programming ? ['蒙版教程', '修图教程'] : ['无关软件速成'],
    planStrategy: '课程身份匹配后，必须结合用户教材、课程目录或考试范围确定真实章节，再生成诊断与计划。',
    catalogNote: '课程身份已人工维护；章节、教师要求与考试范围不作推测。',
    toolFamily,
  })
})
