import { useState } from 'react'
import { courseTypesForStage } from '../data.ts'
import { syllabusText } from '../curriculum.ts'
import type { Course } from '../types.ts'
import type { FieldErrors } from '../providers.ts'
import { Icon } from '../components.tsx'

const stages: Course['stage'][] = ['高中', '大学']
const provinces = ['北京', '上海', '天津', '重庆', '河北', '河南', '山东', '山西', '江苏', '浙江', '安徽', '福建', '江西', '湖北', '湖南', '广东', '广西', '四川', '贵州', '云南', '陕西', '甘肃', '辽宁', '吉林', '黑龙江', '内蒙古', '海南', '青海', '宁夏', '新疆', '西藏', '香港', '澳门', '台湾']
const textbooks = ['人教版', '北师大版', '苏教版', '沪教版', '鲁教版', '湘教版', '粤教版', '其他/自定义目录']

type Props = {
  course: Course
  errors: FieldErrors
  showErrors: boolean
  onUpdate: (patch: Partial<Course>) => void
  onCurriculum: (patch: Partial<Course['curriculum']>) => void
  onResolve: (canonicalId: string) => void
  onDelete: () => void
  onArchive: () => void
  collapsible?: boolean
}

const errorId = (courseId: string, field: string) => `${courseId}-${field}-error`

export function OnboardingCourseForm({ course, errors, showErrors, onUpdate, onCurriculum, onResolve, onDelete, onArchive, collapsible = false }: Props) {
  const [expanded, setExpanded] = useState(!collapsible)
  const error = (field: string) => showErrors ? errors[field] : ''
  const describedBy = (field: string) => error(field) ? errorId(course.id, field) : undefined
  const isSchoolStage = course.stage === '高中'
  const assessmentHelp = course.assessmentMode === 'score' ? '适合考试、测验和补考。' : course.assessmentMode === 'mastery' ? '适合技能或无法用分数表示的课程。' : '适合作品、项目和成果物。'
  const compactSummary = [course.stage, course.courseType, course.assessmentMode === 'score' && course.score !== '' && course.maxScore !== '' ? `${course.score}/${course.maxScore} 分` : ''].filter(Boolean).join(' · ') || '尚未补充课程信息'

  return <article className="form-section course-form" data-course-id={course.id}>
    <header>
      <div><span className="section-kicker">课程事实</span><h2>{course.name || '新课程'}</h2></div>
      <div className="course-form-actions">{collapsible && <button type="button" className="text-button" aria-expanded={expanded} onClick={() => setExpanded(value => !value)}>{expanded ? '收起' : '展开填写'}</button>}<button type="button" className="icon-button danger-icon" aria-label={`删除课程${course.name ? `：${course.name}` : ''}`} title="删除课程" onClick={onDelete}><Icon name="trash" /></button></div>
    </header>

    {collapsible && !expanded ? <p className="course-form-summary">{compactSummary}</p> : <>

    {course.stageStatus === 'needs-reconfirmation' && <div className="inline-notice info" role="status"><span>旧版教育阶段“{course.legacyStage || '未识别'}”已停止使用。请选择高中或大学；如果这门课不再需要，可以归档。</span> <button type="button" className="text-button" onClick={onArchive}>归档课程</button></div>}

    <div className="form-grid two">
      <label className={`field ${error('name') ? 'has-error' : ''}`}><span>课程名称</span><input name={`course-${course.id}-name`} autoComplete="off" value={course.name} aria-invalid={Boolean(error('name'))} aria-describedby={describedBy('name')} onChange={event => onUpdate({ name: event.target.value })} placeholder="例如：高等数学、Photoshop" />{error('name') && <small className="field-error" id={errorId(course.id, 'name')}>{error('name')}</small>}</label>
      <label className={`field ${error('stage') ? 'has-error' : ''}`}><span>教育阶段</span><select name={`course-${course.id}-stage`} value={course.stage} aria-invalid={Boolean(error('stage'))} aria-describedby={describedBy('stage')} onChange={event => onUpdate({ stage: event.target.value as Course['stage'], stageStatus: 'confirmed' })}><option value="">请选择</option>{stages.map(stage => <option key={stage} value={stage}>{stage}</option>)}</select>{error('stage') && <small className="field-error" id={errorId(course.id, 'stage')}>{error('stage')}</small>}</label>
      <label className={`field ${error('courseType') ? 'has-error' : ''}`}><span>课程类型</span><select name={`course-${course.id}-type`} value={course.courseType} disabled={!course.stage} aria-invalid={Boolean(error('courseType'))} aria-describedby={describedBy('courseType')} onChange={event => onUpdate({ courseType: event.target.value as Course['courseType'] })}><option value="">{course.stage ? '请选择' : '请先选择教育阶段'}</option>{courseTypesForStage(course.stage).map(type => <option key={type}>{type}</option>)}</select>{error('courseType') && <small className="field-error" id={errorId(course.id, 'courseType')}>{error('courseType')}</small>}</label>
      {isSchoolStage && <label className={`field ${error('province') ? 'has-error' : ''}`}><span>省份</span><select name={`course-${course.id}-province`} autoComplete="address-level1" value={course.curriculum.province} aria-invalid={Boolean(error('province'))} aria-describedby={describedBy('province')} onChange={event => onCurriculum({ province: event.target.value, examRegion: event.target.value })}><option value="">请选择</option>{provinces.map(value => <option key={value}>{value}</option>)}</select>{error('province') && <small className="field-error" id={errorId(course.id, 'province')}>{error('province')}</small>}</label>}
      {isSchoolStage && <label className={`field ${error('grade') ? 'has-error' : ''}`}><span>年级</span><input name={`course-${course.id}-grade`} autoComplete="off" value={course.curriculum.grade} aria-invalid={Boolean(error('grade'))} aria-describedby={describedBy('grade')} onChange={event => onCurriculum({ grade: event.target.value })} placeholder="例如：高一" />{error('grade') && <small className="field-error" id={errorId(course.id, 'grade')}>{error('grade')}</small>}</label>}
      {isSchoolStage && <label className={`field ${error('semester') ? 'has-error' : ''}`}><span>学期</span><select name={`course-${course.id}-semester`} value={course.curriculum.semester} aria-invalid={Boolean(error('semester'))} aria-describedby={describedBy('semester')} onChange={event => onCurriculum({ semester: event.target.value as Course['curriculum']['semester'] })}><option value="">请选择</option><option>上学期</option><option>下学期</option><option>其他</option></select>{error('semester') && <small className="field-error" id={errorId(course.id, 'semester')}>{error('semester')}</small>}</label>}
      {isSchoolStage && <label className={`field ${error('textbookVersion') ? 'has-error' : ''}`}><span>教材版本</span><select name={`course-${course.id}-textbook`} value={course.curriculum.textbookVersion} aria-invalid={Boolean(error('textbookVersion'))} aria-describedby={describedBy('textbookVersion')} onChange={event => onCurriculum({ textbookVersion: event.target.value, source: event.target.value ? 'preset' : 'unknown' })}><option value="">请选择</option>{textbooks.map(value => <option key={value}>{value}</option>)}</select>{error('textbookVersion') && <small className="field-error" id={errorId(course.id, 'textbookVersion')}>{error('textbookVersion')}</small>}</label>}
      {course.stage === '高中' && <label className="field full-span"><span>选科组合（可选）</span><input name={`course-${course.id}-selection`} value={course.curriculum.subjectSelection.join('、')} onChange={event => onCurriculum({ subjectSelection: event.target.value.split(/[、,，]/).map(item => item.trim()).filter(Boolean) })} placeholder="例如：物理、化学、生物" /></label>}
      {course.stage === '大学' && <><label className={`field ${error('school') ? 'has-error' : ''}`}><span>学校或培养单位</span><input name={`course-${course.id}-school`} autoComplete="organization" value={course.curriculum.school} aria-invalid={Boolean(error('school'))} aria-describedby={describedBy('school')} onChange={event => onCurriculum({ school: event.target.value })} />{error('school') && <small className="field-error" id={errorId(course.id, 'school')}>{error('school')}</small>}</label><label className={`field ${error('major') ? 'has-error' : ''}`}><span>专业</span><input name={`course-${course.id}-major`} autoComplete="off" value={course.curriculum.major} aria-invalid={Boolean(error('major'))} aria-describedby={describedBy('major')} onChange={event => onCurriculum({ major: event.target.value })} />{error('major') && <small className="field-error" id={errorId(course.id, 'major')}>{error('major')}</small>}</label><label className={`field ${error('semester') ? 'has-error' : ''}`}><span>学期</span><select name={`course-${course.id}-university-semester`} value={course.curriculum.semester} aria-invalid={Boolean(error('semester'))} onChange={event => onCurriculum({ semester: event.target.value as Course['curriculum']['semester'] })}><option value="">请选择</option><option>上学期</option><option>下学期</option><option>其他</option></select>{error('semester') && <small className="field-error">{error('semester')}</small>}</label><label className="field"><span>任课教师（可选）</span><input name={`course-${course.id}-instructor`} value={course.curriculum.instructor} onChange={event => onCurriculum({ instructor: event.target.value })} /></label><label className="field full-span"><span>考试形式（可选）</span><input name={`course-${course.id}-exam-format`} value={course.curriculum.examFormat} onChange={event => onCurriculum({ examFormat: event.target.value })} placeholder="例如：闭卷笔试 70%＋平时作业 30%" /></label></>}
      {course.stage === '大学' && <label className="field full-span"><span>教材或课程目录名称</span><input name={`course-${course.id}-syllabus-title`} value={course.curriculum.syllabusTitle} onChange={event => onCurriculum({ syllabusTitle: event.target.value, textbookVersion: event.target.value, source: event.target.value ? 'user-input' : 'unknown' })} placeholder="例如：高等数学（上）课程大纲" /></label>}
      <label className={`field full-span ${error('syllabus') ? 'has-error' : ''}`}><span>章节/模块目录</span><textarea name={`course-${course.id}-syllabus`} rows={4} value={syllabusText(course.curriculum)} aria-invalid={Boolean(error('syllabus'))} aria-describedby={describedBy('syllabus')} onChange={event => onCurriculum({ syllabusUnits: event.target.value.split(/\r?\n/).map(item => item.trim()).filter(Boolean).map((title, index) => ({ id: `unit-${index + 1}`, title, order: index + 1, prerequisites: index ? [`unit-${index}`] : [] })), source: event.target.value.trim() ? 'user-input' : course.curriculum.textbookVersion ? 'preset' : 'unknown' })} placeholder="每行一个章节。基础教育已选常见教材时可留空；大学或自定义课程建议填写。" />{error('syllabus') ? <small className="field-error" id={errorId(course.id, 'syllabus')}>{error('syllabus')}</small> : <small>目录用于限定诊断、任务和资源，系统不会跨教材猜章节。</small>}</label>
    </div>

    {course.ambiguityOptions.length > 0 && !course.ambiguityResolved && <div className="ambiguity-box" role="group" aria-label="确认课程含义"><strong>“{course.name}”有多种含义，请先确认</strong><div>{course.ambiguityOptions.map(option => <button type="button" className="button secondary" key={option.id} onClick={() => onResolve(option.id)}>{option.label}</button>)}</div>{error('ambiguity') && <small className="field-error">{error('ambiguity')}</small>}</div>}

    <fieldset className="assessment-group"><legend>当前水平如何评估</legend><div>{([['score', '考试分数', '有试卷、满分和及格线'], ['mastery', '熟练程度', '用独立完成能力判断'], ['project', '作品/项目', '用成果物和检查项判断']] as const).map(([mode, label, help]) => <button type="button" key={mode} aria-pressed={course.assessmentMode === mode} className={course.assessmentMode === mode ? 'selected' : ''} onClick={() => onUpdate({ assessmentMode: mode })}><strong>{label}</strong><small>{help}</small></button>)}</div><small>{assessmentHelp}</small></fieldset>

    {course.assessmentMode === 'score' ? <div className="form-grid three assessment-fields">
      <label className={`field ${error('score') ? 'has-error' : ''}`}><span>本次得分</span><input name={`course-${course.id}-score`} inputMode="decimal" type="number" min="0" max={course.maxScore || undefined} value={course.score} aria-invalid={Boolean(error('score'))} aria-describedby={describedBy('score')} onChange={event => onUpdate({ score: event.target.value === '' ? '' : Number(event.target.value) })} />{error('score') && <small className="field-error" id={errorId(course.id, 'score')}>{error('score')}</small>}</label>
      <label className={`field ${error('maxScore') ? 'has-error' : ''}`}><span>试卷满分</span><input name={`course-${course.id}-full-score`} inputMode="decimal" type="number" min="1" max="1000" value={course.maxScore} aria-invalid={Boolean(error('maxScore'))} aria-describedby={describedBy('maxScore')} onChange={event => onUpdate({ maxScore: event.target.value === '' ? '' : Number(event.target.value) })} />{error('maxScore') && <small className="field-error" id={errorId(course.id, 'maxScore')}>{error('maxScore')}</small>}</label>
      <label className={`field ${error('passScore') ? 'has-error' : ''}`}><span>及格线</span><input name={`course-${course.id}-pass-score`} inputMode="decimal" type="number" min="0" max={course.maxScore || undefined} value={course.passScore} aria-invalid={Boolean(error('passScore'))} aria-describedby={describedBy('passScore')} onChange={event => onUpdate({ passScore: event.target.value === '' ? '' : Number(event.target.value) })} />{error('passScore') && <small className="field-error" id={errorId(course.id, 'passScore')}>{error('passScore')}</small>}</label>
      <label className={`field ${error('examType') ? 'has-error' : ''}`}><span>考试类型</span><select name={`course-${course.id}-exam-type`} value={course.examType} aria-invalid={Boolean(error('examType'))} aria-describedby={describedBy('examType')} onChange={event => onUpdate({ examType: event.target.value as Course['examType'] })}><option value="">请选择</option>{['期末考试', '补考', '模拟考试', '资格考试', '升学考试', '自测'].map(value => <option key={value}>{value}</option>)}</select>{error('examType') && <small className="field-error" id={errorId(course.id, 'examType')}>{error('examType')}</small>}</label>
      <label className="check-field"><input name={`course-${course.id}-incomplete`} type="checkbox" checked={course.incomplete} onChange={event => onUpdate({ incomplete: event.target.checked })} /><span><strong>缺考或未完成试卷</strong><small>会降低单次成绩的诊断权重</small></span></label>
    </div> : <div className="form-grid two assessment-fields">
      <label className={`field ${error('mastery') ? 'has-error' : ''}`}><span>自评掌握程度</span><select name={`course-${course.id}-mastery`} value={course.mastery} aria-invalid={Boolean(error('mastery'))} aria-describedby={describedBy('mastery')} onChange={event => onUpdate({ mastery: event.target.value as Course['mastery'] })}><option value="">请选择</option>{['刚开始', '几乎不会', '基础薄弱', '一般', '较熟练', '熟练'].map(value => <option key={value}>{value}</option>)}</select>{error('mastery') && <small className="field-error" id={errorId(course.id, 'mastery')}>{error('mastery')}</small>}</label>
      {course.assessmentMode === 'project' && <label className="field"><span>已完成作品数量</span><input name={`course-${course.id}-works`} type="number" min="0" max="99" value={course.completedWorks} onChange={event => onUpdate({ completedWorks: Math.max(0, Number(event.target.value)), projectCompleted: Number(event.target.value) > 0 })} /></label>}
      <label className={`field ${error('mainDifficulty') ? 'has-error' : ''}`}><span>主要卡点</span><input name={`course-${course.id}-difficulty`} value={course.mainDifficulty} aria-invalid={Boolean(error('mainDifficulty'))} aria-describedby={describedBy('mainDifficulty')} onChange={event => onUpdate({ mainDifficulty: event.target.value })} placeholder="例如：离开示例后不知道下一步" />{error('mainDifficulty') && <small className="field-error" id={errorId(course.id, 'mainDifficulty')}>{error('mainDifficulty')}</small>}</label>
      <label className={`field full-span ${error('selfEvidence') ? 'has-error' : ''}`}><span>判断依据</span><textarea name={`course-${course.id}-evidence`} rows={3} value={course.selfEvidence} aria-invalid={Boolean(error('selfEvidence'))} aria-describedby={describedBy('selfEvidence')} onChange={event => onUpdate({ selfEvidence: event.target.value })} placeholder="写下最近一次独立完成任务或作品检查的具体情况" />{error('selfEvidence') && <small className="field-error" id={errorId(course.id, 'selfEvidence')}>{error('selfEvidence')}</small>}</label>
      {course.assessmentMode === 'project' && <label className="field full-span"><span>成果检查项</span><input name={`course-${course.id}-checklist`} value={course.projectChecklist.join('、')} onChange={event => onUpdate({ projectChecklist: event.target.value.split(/[、,，]/).map(item => item.trim()).filter(Boolean) })} placeholder="例如：过程文件完整、命名规范、可说明设计依据" /></label>}
    </div>}
    {course.assessmentMode === 'score' && <div className="form-grid two assessment-fields supplemental-evidence-fields">
      <label className={`field ${error('mastery') ? 'has-error' : ''}`}><span>自评掌握程度</span><select name={`course-${course.id}-mastery`} value={course.mastery} aria-invalid={Boolean(error('mastery'))} aria-describedby={describedBy('mastery')} onChange={event => onUpdate({ mastery: event.target.value as Course['mastery'] })}><option value="">请选择</option>{['刚开始', '几乎不会', '基础薄弱', '一般', '较熟练', '熟练'].map(value => <option key={value}>{value}</option>)}</select>{error('mastery') && <small className="field-error" id={errorId(course.id, 'mastery')}>{error('mastery')}</small>}</label>
      <label className={`field ${error('mainDifficulty') ? 'has-error' : ''}`}><span>主要卡点</span><input name={`course-${course.id}-difficulty`} value={course.mainDifficulty} aria-invalid={Boolean(error('mainDifficulty'))} aria-describedby={describedBy('mainDifficulty')} onChange={event => onUpdate({ mainDifficulty: event.target.value })} placeholder="例如：函数综合题无法独立完成" />{error('mainDifficulty') && <small className="field-error" id={errorId(course.id, 'mainDifficulty')}>{error('mainDifficulty')}</small>}</label>
      <label className={`field full-span ${error('selfEvidence') ? 'has-error' : ''}`}><span>判断依据</span><textarea name={`course-${course.id}-evidence`} rows={3} value={course.selfEvidence} aria-invalid={Boolean(error('selfEvidence'))} aria-describedby={describedBy('selfEvidence')} onChange={event => onUpdate({ selfEvidence: event.target.value })} placeholder="写下最近一次考试或独立完成题目的具体情况" />{error('selfEvidence') && <small className="field-error" id={errorId(course.id, 'selfEvidence')}>{error('selfEvidence')}</small>}</label>
    </div>}
    </>}
  </article>
}
