import type { AppData, Course, LearningResource, LearningTask } from './types.ts'

export const STORAGE_KEY = 'holiday-leap-mvp-v1'

export const todayISO = () => new Date().toISOString().slice(0, 10)

export const addDays = (date: string, days: number) => {
  const value = new Date(`${date}T12:00:00`)
  value.setDate(value.getDate() + days)
  return value.toISOString().slice(0, 10)
}

export const createCourse = (overrides: Partial<Course> = {}): Course => ({
  id: crypto.randomUUID(),
  name: '',
  stage: '',
  courseType: '',
  score: '',
  maxScore: '',
  passScore: '',
  examType: '',
  incomplete: false,
  mastery: '',
  goalType: '',
  targetScore: '',
  targetDate: '',
  priority: false,
  desiredResult: '',
  ...overrides,
})

export const verifiedResources: LearningResource[] = [
  {
    id: 'resource-baseline-calculus',
    title: '15 分钟高等数学基础诊断',
    platform: '站内测验',
    author: '假期跃迁学习设计组',
    durationMin: 15,
    suitableStage: '大学 · 基础诊断',
    knowledgePoints: ['代数基础', '函数', '极限', '导数'],
    recommendation: '先确定失分来自先修基础还是微积分概念，再决定学习顺序。',
    humanVerified: true,
    url: '/diagnosis#baseline-quiz',
    status: '可用',
  },
  {
    id: 'resource-mit-calculus',
    title: 'Single Variable Calculus',
    platform: 'MIT OpenCourseWare',
    author: 'Prof. David Jerison · MIT OpenCourseWare',
    durationMin: 60,
    suitableStage: '大学 · 系统学习',
    knowledgePoints: ['函数', '极限', '导数', '积分'],
    recommendation: '课程包含讲义、视频、习题与答案，适合按章节系统补基础。',
    humanVerified: true,
    url: 'https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/',
    status: '可用',
  },
  {
    id: 'resource-khan-differential',
    title: 'Differential Calculus',
    platform: 'Khan Academy',
    author: 'Khan Academy',
    durationMin: 45,
    suitableStage: '大学 · 分知识点练习',
    knowledgePoints: ['极限', '连续', '导数', '导数应用'],
    recommendation: '知识点拆分细，并配有即时练习，适合针对薄弱环节补漏。',
    humanVerified: true,
    url: 'https://www.khanacademy.org/math/calculus/differential-calculus',
    status: '可用',
  },
  {
    id: 'resource-bilibili-tongji',
    title: '同济大学：高等数学（三）',
    platform: '哔哩哔哩',
    author: '弋恪（页面上传者）',
    durationMin: 50,
    suitableStage: '大学 · 中文课程',
    knowledgePoints: ['向量', '空间解析几何', '多元函数'],
    recommendation: '中文讲授，适合需要配合国内课程体系复习的学习者。',
    humanVerified: true,
    url: 'https://www.bilibili.com/video/BV1ss411K722/',
    status: '可用',
  },
]

export const createTask = (overrides: Partial<LearningTask> = {}): LearningTask => ({
  id: crypto.randomUUID(),
  date: todayISO(),
  time: '09:00',
  title: '高等数学基础诊断',
  courseId: 'course-calculus',
  knowledgePoint: '代数基础与函数',
  resourceId: 'resource-baseline-calculus',
  materialLabel: '15 分钟高等数学基础诊断',
  watchMinutes: 15,
  practiceCount: 6,
  quizTask: '完成 6 道基础定位题',
  completionCriteria: '提交全部题目并查看薄弱知识点',
  estimatedMinutes: 35,
  status: '待完成',
  skipReason: '',
  changeNote: '根据初始诊断安排',
  order: 0,
  ...overrides,
})

const defaultCourse: Course = {
  id: 'course-calculus',
  name: '高等数学',
  stage: '大学',
  courseType: '必修课',
  score: 58,
  maxScore: 100,
  passScore: 60,
  examType: '期末考试',
  incomplete: false,
  mastery: '基础薄弱',
  goalType: '补弱',
  targetScore: 75,
  targetDate: addDays(todayISO(), 42),
  priority: true,
  desiredResult: '能独立完成函数、极限与基础导数题。',
}

export const initialData = (): AppData => ({
  version: 1,
  onboardingCompleted: false,
  courses: [defaultCourse],
  schedule: {
    holidayStart: todayISO(),
    holidayEnd: addDays(todayISO(), 42),
    weekdayMinutes: 120,
    weekendMinutes: 150,
    preferredTimes: ['上午'],
    travelDates: '',
    fixedCommitments: '',
    restDays: ['周日'],
    maxFocusMinutes: 45,
    interruptionReason: '临时出行与手机分心',
  },
  resources: verifiedResources.map(resource => ({ ...resource })),
  tasks: [
    createTask(),
    createTask({
      id: 'task-limit-intro',
      date: todayISO(),
      time: '14:30',
      title: '极限概念与图像判断',
      knowledgePoint: '极限',
      resourceId: 'resource-khan-differential',
      materialLabel: 'Differential Calculus · Limits and continuity',
      watchMinutes: 20,
      practiceCount: 8,
      quizTask: '完成 5 道极限图像判断题',
      completionCriteria: '正确率达到 70%，并记录错因',
      estimatedMinutes: 50,
      order: 1,
    }),
    createTask({
      id: 'task-function-review',
      date: todayISO(),
      time: '19:30',
      title: '函数基础回补',
      knowledgePoint: '函数',
      resourceId: 'resource-mit-calculus',
      materialLabel: 'Single Variable Calculus · Functions',
      watchMinutes: 25,
      practiceCount: 6,
      quizTask: '完成函数定义域与图像小测',
      completionCriteria: '6 道练习至少答对 5 道',
      estimatedMinutes: 45,
      order: 2,
    }),
  ],
  diagnosis: null,
  progress: {
    initialAccuracy: 38,
    weeklyAccuracy: 61,
    masteryBefore: 24,
    masteryNow: 46,
    wrongAnswers: 17,
    repeatedWeakPoints: ['函数定义域', '极限等价替换'],
    actualStudyMinutes: 315,
    resourceCompleted: 4,
    resourceTotal: 7,
    nextWeekReason: '极限题正确率仍低于 70%，下周增加基础练习并减少新知识点。',
    nextWeekAppliedAt: '',
  },
  settings: {
    displayName: '学习者',
    reminderTime: '08:30',
    resourcePreference: '系统课程 + 练习',
    acceptShortVideo: false,
    dailyReminder: true,
    adjustmentReminder: true,
    privacyAccepted: true,
  },
  coachMessages: [{ id: 'coach-welcome', role: 'coach', text: '告诉我最近的时间变化，我会解释影响并重排剩余任务。', createdAt: new Date().toISOString() }],
  planChanges: ['已为每天保留至少 30 分钟缓冲时间。'],
})
